### ISSUE TITLE
Possible improvements - Torque heatmap - 

### ISSUE THREAD

**Issue by ekonlab** [CartoDB/torque#110]
As per my experience with heatmaps. I would suggest to include the next features as optional in the heatmap:

- radius - radius of each "point" of the heatmap, 25 by default (https://github.com/Leaflet/Leaflet.heat)
- blur - amount of blur, 15 by default (https://github.com/Leaflet/Leaflet.heat)
- color scales: https://github.com/mbostock/d3/wiki/Ordinal-Scales &  https://github.com/mbostock/d3/wiki/Quantitative-Scales
- alpha

**Comment by saleiva** [comment]
This should go to the cartodb repo :)

**Comment by ekonlab** [comment]
Ok, sorry for the mistake. I will move it to this repo.
