### ISSUE TITLE
heatmap not working on IE9

### ISSUE THREAD

**Issue by javisantana** [CartoDB/torque#130]
nothing is displayed, dunno if it's due performance:

https://team.cartodb.com/u/javi/viz/d08278f8-b063-11e4-bac3-0e853d047bba/public_map

**Comment by fdansv** [comment]
So... after a bit of research, I found out that IE9's ["special" way](http://stackoverflow.com/questions/16966758/can-xdomainrequest-be-used-to-load-and-draw-images) of handling cross-domain requests means that only ```text/plain``` content can be requested using CORS. Which means that unless we keep the marker image file on the same domain, we're not able to support heatmaps on Internet Explorer 9 and below.
