### ISSUE TITLE
time slider showing for mobile torque map with one step

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/torque#134]
The time slider and play/pause button appear on the mobile version of a one step Torque map. Wasn't the slider removed for these maps?

![img_1172](https://cloud.githubusercontent.com/assets/1041056/6371779/e0744456-bccc-11e4-80af-72f41e05b101.PNG)

**Comment by javisantana** [comment]
this is a cartodb.js issue, please move there

**Comment by ohasselblad** [comment]
@javisantana : moved
