### ISSUE TITLE
show date (or number) range for small time steps

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/torque#135]
When creating a torque map for a small number of steps, it would be good to show the date range in a legend or in the slider bar. For example, if the data is aggregated into three time steps from 1 Jan - 31 Jan, the slider would show `1 Jan - 10 Jan` for the first step, `11 Jan - 20 Jan` for the second, and `21 Jan - 31 Jan` for the third. For a one step map, the slider could turn into a legend showing the date range for the data.

@fdansv what do you think?

**Comment by fdansv** [comment]
@ohasselblad what would you consider a reasonable minimum range to show this instead of just one date?

**Comment by ohasselblad** [comment]
What about this?

1. One day (ignoring hours) when the time is not being shown: 1 Jan - 2 Jan
2. On the level of a day, maybe show a range in hours? 1 Jan, 08:00 - 09:00

**Comment by fdansv** [comment]
I've done it for dates so far:

![ranges](https://cloud.githubusercontent.com/assets/3707222/7255723/61257882-e84b-11e4-8d74-55ef7c16152b.gif)

**Comment by fdansv** [comment]
Whoops, accidental close

**Comment by fdansv** [comment]
Well actually this is a cartodb.js issue, I'll open a PR there.

**Comment by fdansv** [comment]
This was added in #450
