### ISSUE TITLE
provider url_template

### ISSUE THREAD

**Issue by karelcallens** [CartoDB/torque#136]
The API documentation mentions a provider 'url_template'. 
However I cannot seem to get the 'leaflet.html' example working.

**Comment by fdansv** [comment]
@karelcallens if you could point at me at the code you used and elaborate on how is it not working, that'd be great!

**Comment by karelcallens** [comment]
line 31 in leaflet.html points to L.TiledTorqueLayer which is undefined

**Comment by fdansv** [comment]
url_template is deprecated, as it doesn't use the torque tile format. Follow the progress of https://github.com/CartoDB/torque/issues/220 for the provider that will fulfill its purpose
