### ISSUE TITLE
Data peeking infowindow

### ISSUE THREAD

**Issue by fdansv** [CartoDB/torque#139]
As discussed with @saleiva, it'd be nice to think about a UI element that gives an insight into what's being rendered with Torque. In Sergio's example, when hovering the mouse pointer over a cell in the map, an infowindow reveals some sort of aggregation of the data in it.

**Comment by javisantana** [comment]
https://github.com/CartoDB/torque/blob/master/lib/torque/leaflet/torque.js#L369

**Comment by fdansv** [comment]
\o/

**Comment by saleiva** [comment]
So so??? ;)

**Comment by ohasselblad** [comment]
+1000

**Comment by fdansv** [comment]
The torque part for this is done and merged to master, moving on to frontend.

**Comment by fullofcaffeine** [comment]
I'm currently wondering about this (how to show infowindows for a stopped torque frame). I don't need infowindows when the animation is playing, but when the user stops it to explore the data on the map. I couldn't figure out a way to do so using the Carodb editor. How could I integrate change with my cartodb data and show infowindows? Is it documented anywhere?

**Comment by fdansv** [comment]
@fullofcaffeine right now this isn't supported on the editor, but there is a DIY example here:

https://github.com/CartoDB/torque/blob/master/examples/data_peek.html

**Comment by fullofcaffeine** [comment]
@fdansv Great, thanks for the link and for the quick response!
