### ISSUE TITLE
be able to pause animation at final frame

### ISSUE THREAD

**Issue by abenrob** [CartoDB/torque#140]
I am doing a short cumulative torque animation, and the impact of the final coverage/quantity is lost when it loops (or on loop=false, when resets to 0 frame.

I modified the Animator function to accept option 'pauseMax,' 
```
this.options = torque.extend({
    animationDelay: 0,
    maxDelta: 0.2,
    loop: options.loop === undefined ? true : options.loop,
    pauseMax: options.pauseMax === undefined ? false : options.pauseMax
}, this.options);
```
and then in Animator._tick I caught that flag, and requested the final frame then paused the animation, prior to the time reset to 0.

```
_tick: function() {
  var t1 = +new Date();
  var delta = (t1 - this._t0)*0.001;
  // if delta is really big means the tab lost the focus
  // at some point, so limit delta change
  delta = Math.min(this.options.maxDelta, delta);
  this._t0 = t1;
  this._time += delta;
  if(this.step() >= this.options.steps) {
    // if we set pauseMax...
    if(this.options.pauseMax){
        // set time to max time
        this.time(this.options.animationDuration);
        // go to final frame (callback to nothing)
        requestAnimationFrame(function(){});
        // pause at final frame
        this.pause();
    } else {
        this._time = 0;
        if(!this.options.loop){
          this.stop();
        }
    }
  }
  if(this.running) {
    this.time(this._time);
    requestAnimationFrame(this._tick);
  }
}
```

Would be interested to know your approach to this, and would be happy to open a pull if I can accomodate that approach.

**Comment by javisantana** [comment]
maybe when loop = false the time should stop at last frame?

**Comment by abenrob** [comment]
That what I hoped it would do...
For non-cumulative uses the reset at beginning might be desirable?
Also this.stop() resets to beginning and ends the animation, while pause doesn't, so it would need to change in both places.
Another issue is that torque might loop to the 0 frame without hitting the last frame. If I have 512 frames in a 4 second animation, it might advance from 506 to 0, which is why I am setting the time to the end and requesting that final frame 
```
// set time to max time
this.time(this.options.animationDuration);
// go to final frame (callback to nothing)
requestAnimationFrame(function(){});
```

**Comment by javisantana** [comment]
> For non-cumulative uses the reset at beginning might be desirable? 

I think so

> Another issue is that torque might loop to the 0 frame without hitting the last frame. If I have 512 frames in a 4 second animation, it might advance from 506 to 0, which is why I am setting the time to the end and requesting that final frame

why don't apply this behavior to the loop option? 

I think the loop option should do exactly what you propose so I'd remove it and would change the pauseMax to loop.

Sounds good?

**Comment by abenrob** [comment]
I can update the source - should I make all, or leave that to you?

**Comment by javisantana** [comment]
it would be nice if you could do a PR

**Comment by fdansv** [comment]
This was added in #141 above :)
