### ISSUE TITLE
Should resolutions <= 0 fail?

### ISSUE THREAD

**Issue by rochoa** [CartoDB/torque#151]
Does it make sense to allow to pass a resolution <= 0?
 - With resolution < 0 no data will be returned.
 - With resolution = 0 some providers will fail due to a division by 0 (for instance windshaft provider query won't work).

**Comment by rochoa** [comment]
related: https://github.com/CartoDB/torque/issues/47

**Comment by fdansv** [comment]
I do think they should fail, but maybe as a 400 from the server? It'd make sense with what we've been doing so far.

**Comment by rochoa** [comment]
+1 for the `400`.

**Comment by fdansv** [comment]
OK then since we're dealing with this server-side let's close this and keep tracking on Windshaft.
