### ISSUE TITLE
Torque category is not taking into account marker-file

### ISSUE THREAD

**Issue by iriberri** [CartoDB/torque#152]
/** torque_cat visualization */

Map {
-torque-frame-count:512;
-torque-animation-duration:30;
-torque-time-attribute:"cartodb_id";
-torque-aggregation-function:"CDB_Math_Mode(torque_category)";
-torque-resolution:2;
-torque-data-aggregation:linear;
}

#ne_10m_populated_places_simple_15{
  comp-op: source-over;
  marker-fill-opacity: 0.9;
  marker-line-color: #FFF;
  marker-line-width: 1.5;
  marker-line-opacity: 1;
  marker-type: ellipse;
  marker-width: 6;
  marker-fill: #FF9900;
}
#ne_10m_populated_places_simple_15[frame-offset=1] {
 marker-width:8;
 marker-fill-opacity:0.45; 
}
#ne_10m_populated_places_simple_15[frame-offset=2] {
 marker-width:10;
 marker-fill-opacity:0.225; 
}
#ne_10m_populated_places_simple_15[value=1] {
    marker-file: url(https://s3.amazonaws.com/com.cartodb.users-assets.production/production/iriberri/assets/20150107230219red-heart-icon.png);
}
#ne_10m_populated_places_simple_15[value=2] {
   marker-fill: #7B00B4;
    marker-file: url(https://s3.amazonaws.com/com.cartodb.users-assets.production/production/iriberri/assets/20150107230219red-heart-icon.png);
}

This renders:
![image](https://cloud.githubusercontent.com/assets/1730320/6527615/59ad81d8-c41c-11e4-91cb-d45da00ffd8a.png)

**Comment by fdansv** [comment]
We need to narrow this down to replicate it, as it does work for me in production

**Comment by iriberri** [comment]
Let me check again this viz!

**Comment by iriberri** [comment]
In torque perfect:

![image](https://cloud.githubusercontent.com/assets/1730320/6552201/9fc4133e-c643-11e4-8030-46562d582d90.png)

In Category:
![image](https://cloud.githubusercontent.com/assets/1730320/6552216/cd789eb2-c643-11e4-8891-3365df7b8930.png)

**Comment by iriberri** [comment]
http://gis.stackexchange.com/questions/138119/custom-icons-for-torque-categories-in-cartodb

**Comment by RaulVila** [comment]
Hi, you can check it here:
http://cdb.io/1wa6e3x

Thank you very much!

**Comment by fdansv** [comment]
@iriberri can you pass me a link to the vis in particular? I'm still having trouble replicating this :)

**Comment by iriberri** [comment]
Unable to replicate now :/

https://team.cartodb.com/u/iriberri/viz/7a08b880-ea5f-11e4-bee5-0e8dde98a187/embed_map

**Comment by iriberri** [comment]
@RaulVila are you still experiencing the issue? If it's the case, could you send us a specific example? If not, I'd close this for the moment being.

**Comment by RaulVila** [comment]
On Chrome It's working for me too, but in Firefox (37.0.2) the animation stops at a random number between 3 and 17 (aprox).
I've attached a screenshot.

![cartodb-firefox-torque-error](https://cloud.githubusercontent.com/assets/11410952/7345318/bc98f590-ecd3-11e4-8dd5-50a8458e9fd1.png)

Thanks!

**Comment by fdansv** [comment]
@RaulVila thanks for the quick reply ;) This seems like a completely different issue, so if you can open a new ticket describing it and linking the exact visualisation where it's happening, if possible, that' be great!

Closing until we're able to clearly reproduce it.
