### ISSUE TITLE
Add setInteractivity method to Torque

### ISSUE THREAD

**Issue by fdansv** [CartoDB/torque#158]
Related to #139 and https://github.com/CartoDB/cartodb/issues/2753 . This will allow Torque to trigger InfoWindows when it's being called from Cartodb.js.

**Comment by rochoa** [comment]
Does this make sense?

We dropped support in Windshaft for interactivity in torque layers: https://github.com/CartoDB/Windshaft/blob/master/doc/MapConfig-1.3.0.md#130

**Comment by fdansv** [comment]
The name is not final, since the interactivity takes place in a CartoDB layer, not in the torque one, but we need the interface between it and Torque to add these https://github.com/CartoDB/torque/pull/156

**Comment by fdansv** [comment]
Since it isn't Torque the one showing the infowindows, but cartodb.js, I don't see anymore how this method would be of any real use. Its functionality in Cartodb.js is mostly related to the fields attached to a feature, which Torque isn't concerned with.
