### ISSUE TITLE
Torque minimum granularity blocked to 4 minutes

### ISSUE THREAD

**Issue by iriberri** [CartoDB/torque#159]
Spotted in Torque cat but also happening in the regular Torque wizard.

Ranges for the data:
max
1865-04-02T18:29:00Z
min
1865-04-02T12:00:00Z

We tried adding some years in order to maintain the epoch timestamps as positive numbers:
max
2005-04-02T18:29:00Z
min
2005-04-02T12:00:00Z

If you reduce the steps to small values, this is correct. Once you pass 100 frames it gets blocked to 4 mins no matter which big number you use there.

Sample of CartoCSS:
````
/** torque visualization */

Map {
-torque-frame-count:2048;
-torque-animation-duration:10;
-torque-time-attribute:"nueva_hora";
-torque-aggregation-function:"count(cartodb_id)";
-torque-resolution:2;
-torque-data-aggregation:linear;
}

#lumpkin_points_final{
  comp-op: lighter;
  marker-fill-opacity: 0.9;
  marker-line-color: #FFF;
  marker-line-width: 1.5;
  marker-line-opacity: 1;
  marker-type: ellipse;
  marker-width: 6;
  marker-fill: #FF9900;
}
#lumpkin_points_final[frame-offset=1] {
 marker-width:8;
 marker-fill-opacity:0.45; 
}
#lumpkin_points_final[frame-offset=2] {
 marker-width:10;
 marker-fill-opacity:0.225; 
}
````

CSV sample attached [here](https://gist.github.com/iriberri/06cc49010cf2725eece9). Category column should be type number and the dates columns of type date.

**Comment by fdansv** [comment]
Closing this since it isn't a problem with granularity. If the issue can be replicated let's open a new issue regarding it.
