### ISSUE TITLE
loop option not working

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/torque#164]
The `loop: false` option does not seem to work with standard configurations. See [this map](http://bl.ocks.org/ohasselblad/f3b8f575312d29248ffa) to see it live.

Option listed in the docs: https://github.com/CartoDB/torque/blob/master/doc/API.md#cartodb-data-options-sql-api-provider

It uses the following config:
```js
var layerSource = {
              type: 'torque',
              options: {
                  table_name: tableName,
                  user_name: userName,
                  cartocss: $("#cartocss").html(),
                  loop: false
              }
          }
```

**Comment by fdansv** [comment]
Hmm... that example isn't working:

![screen shot 2015-04-21 at 10 54 23](https://cloud.githubusercontent.com/assets/3707222/7248678/e57442c6-e814-11e4-96b0-b7667443faca.png)

**Comment by ohasselblad** [comment]
whoops, should be working now.
