### ISSUE TITLE
no errors for badly formed aggregate functions

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/torque#165]
Errors from badly formed aggregate functions in `-torque-aggregation-function` are never reported in my experience. Plans for reporting errors or warnings?

Other functions seem well-formed but fail to let markers show on maps... error reporting would help debug these functions.

**Comment by rochoa** [comment]
The tiler returns an error in some cases:
- [function does not exist](https://rochoa.cartodb.com/api/v1/map?config=%7B%22version%22%3A%221.0.1%22%2C%22stat_tag%22%3A%226fbf4fc0-dd2a-11e4-b95c-0e0c41326911%22%2C%22layers%22%3A%5B%7B%22type%22%3A%22torque%22%2C%22options%22%3A%7B%22cartocss_version%22%3A%221.0.0%22%2C%22cartocss%22%3A%22Map%7B-torque-frame-count%3A512%3B-torque-resolution%3A2%3B-torque-aggregation-function%3A%27counttt(cartodb_id)%27%3B-torque-time-attribute%3A%27cartodb_id%27%3B-torque-data-aggregation%3Alinear%3B%7D%22%2C%22sql%22%3A%22select%20*%20from%20untitled_table_10%22%7D%7D%5D%7D)
- [column does not exist](https://rochoa.cartodb.com/api/v1/map?config=%7B%22version%22%3A%221.0.1%22%2C%22stat_tag%22%3A%226fbf4fc0-dd2a-11e4-b95c-0e0c41326911%22%2C%22layers%22%3A%5B%7B%22type%22%3A%22torque%22%2C%22options%22%3A%7B%22cartocss_version%22%3A%221.0.0%22%2C%22cartocss%22%3A%22Map%7B-torque-frame-count%3A512%3B-torque-resolution%3A2%3B-torque-aggregation-function%3A%27count(cartodbid)%27%3B-torque-time-attribute%3A%27cartodb_id%27%3B-torque-data-aggregation%3Alinear%3B%7D%22%2C%22sql%22%3A%22select%20*%20from%20untitled_table_10%22%7D%7D%5D%7D)

However it seems the editor doesn't propagate those errors. So not sure if it's something specific for torque or for the editor.

**Comment by ohasselblad** [comment]
thanks @rochoa 
i guess i duplicated this in #169
