### ISSUE TITLE
Pixels at edge form gap

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/torque#167]
I reported this previously, but can't find the ticket so sorry if dup

https://team.cartodb.com/u/andrew/viz/c363d36a-de4e-11e4-8717-0e853d047bba/embed_map

![screen shot 2015-04-08 at 8 25 04 pm](https://cloud.githubusercontent.com/assets/370259/7058288/6d886436-de2d-11e4-8e0c-8faa8c6e0dae.png)

Make the marker-width: 6 and the -torque-resolution:12

**Comment by rochoa** [comment]
Did you check this one: https://github.com/CartoDB/Windshaft/issues/308 ?

**Comment by fdansv** [comment]
@rochoa I think this is a client issue. Back in #142 we changed the exact position where points are drawn. This might have to do with it. Will report back.

**Comment by fdansv** [comment]
This issue appears when a resolution not power of 2 is set. Right now we limit the possible values to powers of two in the editor, but there's nothing preventing the user from setting any in the carto style. As discussed with @javisantana, we should document this glitch and recommend the use of powers of two.

**Comment by fdansv** [comment]
Ha, actually this is indeed already documented:

https://github.com/CartoDB/torque-reference/blob/master/1.0.0/reference.json#L51

Closing!
