### ISSUE TITLE
.error not catching errors?

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/torque#169]
When I give a torque layer a bad CartoCSS config, I get:
`Uncaught TypeError: Cannot read property 'torque' of undefined`

Digging into the returned URL, I find:
`_cdbct_0_1({"errors":["TorqueRenderer: Layer query did not return the requested time-attribute column 'undefined'"]});`

Should this be reported via `.error(function(err) { console.log(err); "})` instead of having to dig through the console like this?

Something similar happens for a `table_name: 'non_existent_table'` when the table doesn't exist.

**Comment by fdansv** [comment]
As discussed with @javisantana, this is to do with torque looking for an "error" json key instead of "errors", so it should be a simple fix. Will try to get it sorted today.
