### ISSUE TITLE
Torque heat map displays as static on web & animation on phone; phone version does not display.

### ISSUE THREAD

**Issue by LoganWinston** [CartoDB/torque#171]
@fdansv 
> http://www.cpr.org/news/story/meth-use-colorado-has-police-and-outreach-groups-scrambling

> 
![img_3006](https://cloud.githubusercontent.com/assets/6501319/7204318/32d5ad76-e4ef-11e4-8b9d-d07aa6c431a7.PNG)

**Comment by fdansv** [comment]
@LoganWinston hey! please specify device and browser ;)

**Comment by fdansv** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines
