### ISSUE TITLE
UNIX timestamps should be converted to date-time in the timeslider

### ISSUE THREAD

**Issue by fdansv** [CartoDB/torque#173]
@javisantana I was playing with your Nurburgring example, which has its ```time``` column in UNIX timestamps. This is how the timeslider looks with ```time``` selected:

![screen shot 2015-04-21 at 11 57 46](https://cloud.githubusercontent.com/assets/3707222/7249850/b99c082e-e81d-11e4-8800-45933cb056c8.png)

Which isn't massively informative. Should we make timestamps human readable?

**Comment by ohasselblad** [comment]
if the 'time' column is not a date format, doesn't the timeslider show the step number instead of a value in the time column?

**Comment by rochoa** [comment]
You could always change the query to `to_timestamp(time) t_time` and use `t_time` as `-torque-time-attribute`, couldn't you?

**Comment by fdansv** [comment]
Yeah but that needs to be done by the user, which isn't the intent of this. After discussing with @javisantana there's not much we can do from the client side perspective.
