### ISSUE TITLE
misleading error when table is set to private or non-existent

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/torque#174]
Using a table name that doesn't exist or is set to private, I get the following error:

```
Uncaught TypeError: Cannot read property 'torque' of undefined
```
![screen shot 2015-04-21 at 08 51 40](https://cloud.githubusercontent.com/assets/1041056/7252503/ab47c4f8-e803-11e4-8dee-2a6126cd1a16.png)

Should it throw an error like, `The table "table_name" requested either does not exist or is set to private.`

**Comment by fdansv** [comment]
Errors are handled by using the .error() function, which should provide the list of errors as argument.
