### ISSUE TITLE
getValueForPos() not returning the expected value

### ISSUE THREAD

**Issue by fullofcaffeine** [CartoDB/torque#176]
I already posted about it in the cartodb google group, here: https://groups.google.com/forum/#!topic/cartodb/nonrmLM6-go

Basically, I'm not getting the value I expect from ```getValueFromPos()```. I have a ````-torque-aggregation-function:"sum(revenue)"```` rule, and the ```revenue``` field in the table is set to 4500 for all records (for testing purposes), but I'm getting what seem to be arbitrary values:

https://www.dropbox.com/s/6jf1h6rfktr68ju/Screenshot%202015-04-23%2018.55.14.png?dl=0

Am I misunderstanding something?

**Comment by fdansv** [comment]
@fullofcaffeine would it be possible for you to show us the example you're working with? It would really help.

**Comment by fullofcaffeine** [comment]
@fdansv https://github.com/fullofcaffeine/carto_torque_test

Let me know if you need anything else.

**Comment by fullofcaffeine** [comment]
I've changed it to be served with Rack so I could put on Heroku, for your convenience: http://pacific-inlet-5306.herokuapp.com/.

**Comment by fullofcaffeine** [comment]
Check the console for the values. I'm expecting them to be much larger, since it's based off the revenue column.

**Comment by fullofcaffeine** [comment]
@fdansv It just occurred to me that this might be because Torque doesn't support Heatmaps that represent distribution of values, but only density (concentration of points). Is that why? If so, is there a way to base the heatmap out of a specific attribute, and if not, do you plan on adding this feature soon?

Reference: http://gis.stackexchange.com/questions/256/how-to-build-effective-heat-maps

**Comment by fdansv** [comment]
@fullofcaffeine I think this is due to something we were discussing the other day. Basically values in Torque right now are capped between 0 and 255, since we use an 8 bit integer array to store them. I'd like to change that soon by specifying max and min values on the layergroup like we do with dates. But for now I'd recommend you to normalise your value data, if possible, to values between 0 and 255 and remap them in the client.

Does that make sense?

**Comment by fullofcaffeine** [comment]
@fdansv Could you give me an example of doing that?

**Comment by fdansv** [comment]
Sure, say that you have a column *revenue* with these values:
```
1700
260
30
520
```

You could create a new column where those values are mapped to a range between 0 and 255, with the following expression:

```
mappedValue = 255 * ((value - minValue) / (maxValue - minValue))
```

Use that in torque-aggregate-function, and, using getValueFromPos():

```
realValue = minValue + (maxValue - minValue) * (getValueFromPos(x,y) / 255)
```

In this case, minValue and maxValue would be 30 and 1700 respectively.

**Comment by fullofcaffeine** [comment]
Oh, a linear map. Got it.
