### ISSUE TITLE
Torque animation crashes in Firefox

### ISSUE THREAD

**Issue by RaulVila** [CartoDB/torque#177]
Detected on the resolution of issue 152:
https://github.com/CartoDB/torque/issues/152#issuecomment-96640282

The torque animated map used for testing worked perfectly in Chrome, but in Firefox it crashes (see attachment).

![bc98f590-ecd3-11e4-8dd5-50a8458e9fd1 1](https://cloud.githubusercontent.com/assets/11410952/7348604/33020fa4-ecf3-11e4-9fea-dd4b4617b3f7.png)

**Comment by fdansv** [comment]
@RaulVila can you pass me the link to the visualisation please?

**Comment by RaulVila** [comment]
No, sorry, it was a Carla Iriberri visualization and it's no longer available:
https://team.cartodb.com/u/iriberri/viz/22bd12f2-ecc0-11e4-962b-0e9d821ea90d/embed_map

**Comment by iriberri** [comment]
Ops, sorry so much :(

Replicated it here:

https://team.cartodb.com/u/iriberri/viz/b0b3eafe-ef1d-11e4-b6c7-0e018d66dc29/embed_map

Could you try to access via HTTP and check the errors there too?

http://team.cartodb.com/u/iriberri/viz/b0b3eafe-ef1d-11e4-b6c7-0e018d66dc29/embed_map

**Comment by fdansv** [comment]
Cool, #180 solves it :)

**Comment by RaulVila** [comment]
It's still failing in my firefox (v37.0.2 on Windows 8.1), maybe the fix is not deployed on production...
(both versions: https & http)
![cartodb-torque-firefox-error](https://cloud.githubusercontent.com/assets/11410952/7413351/33797198-ef4b-11e4-8a0c-e80e8e594ebd.png)

**Comment by fdansv** [comment]
Ha, it isn't even merged to Torque yet! It will be on production on Monday.

**Comment by fdansv** [comment]
#180 merged, closing!
