### ISSUE TITLE
Increase timeout of jsonp requests to 45s

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/torque#198]
We're seeing some errors in Track.js that indicate that jsonp requests are "timing out" when trying to instantiate a map. [We are currently setting a timeout of 10s](https://github.com/CartoDB/torque/blob/master/lib/torque/request.js#L7) for this requests but they can take up to 45s. The problem is that [we're cleaning all the jsonp stuff](https://github.com/CartoDB/torque/blob/master/lib/torque/request.js#L31) after 10s and so, when the requests comes back and tries to execute the callback we defined in `window`, [it no longer exists](https://github.com/CartoDB/torque/blob/master/lib/torque/request.js#L21) and throws:

```
Uncaught ReferenceError: _cdbct_1346791484_1 is not defined
```

It's occurring mostly on Android devices.

We need to increase that "timeout" to make it consistent with the maximum response time that the tiler provides.

cc/ @fdansv @javisantana

**Comment by javisantana** [comment]
There should be a way to stop it or just replace the callback by a dummy function so it does not fail, right?

**Comment by alonsogarciapablo** [comment]
Yes, if we could also stop the request that would be great :) Otherwise, we need to keep that `window[fnName]` so that it doesn't throw a js error. As @javisantana proposes, we can replace it with something that doesn't invoke the callback...
