### ISSUE TITLE
User and /or Table Map binding problem ? for timelapse map

### ISSUE THREAD

**Issue by ergum** [CartoDB/torque#203]
Hi.

I tried to use that idea with torque.js: http://zevross.com/blog/2014/05/15/an-example-of-using-torque-cartodbs-time-lapse-tool/ with my own Map data in CartoDB, changing the user, table and CARTOCSS but something goes wrong. It doesn’t work and the console log said: Uncaught TypeError: Cannot read property ‘torque’ of undefined.

Demo: http://lacrafteria.es/aguas/

It looks like the API doesn’t recognize my user and/or table. Any idea or suggestion?

Thanks.

**Comment by fdansv** [comment]
Hey @ergum, you seem to be using a very old version of Torque. Can I ask you to use the current one? With [this distribution](https://github.com/CartoDB/torque/blob/master/dist/torque.full.uncompressed.js) you won't need to add Underscore or Carto. Regarding access to your table, is it possible that your table is private?
