### ISSUE TITLE
layer.play and layer.pause don't change ui image

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/torque#213]
I've experience the same thing as this user before:
http://gis.stackexchange.com/questions/158238/disabling-torque-autoplay-resetting-ui

**Comment by knownasilya** [comment]
Also seeing this as well.

**Comment by knownasilya** [comment]
Looks like the Google Maps torque file doesn't setup the default on* functions.

google maps: https://github.com/CartoDB/torque/blob/be7046e5a0145b860a3d8840c20ef4ec6e65ef5b/lib/torque/gmaps/torque.js#L35

vs Leaflet: https://github.com/CartoDB/torque/blob/be7046e5a0145b860a3d8840c20ef4ec6e65ef5b/lib/torque/leaflet/torque.js#L45
