### ISSUE TITLE
render several keys/steps

### ISSUE THREAD

**Issue by rochoa** [CartoDB/torque#246]
**Value**: Having a method to freeze the visualisation and display all the available data is useful when you want to compare against other static representations of the data.

TODO
 - [x] Support for rendering several keys/steps at low level
 - [x] Expose a new public method to render a range: start step, end step.

cc @viddo

**Comment by javisantana** [comment]
FYI: there was originally a setKeys what allowed to set more than one key to render.

Don't confuse cumulative mode (which aggregates the data) with render more than one frame

**Comment by rochoa** [comment]
Oh, I was misunderstanding the problem then. Thanks for the heads up :smile:
