### ISSUE TITLE
polygons don't seem to work

### ISSUE THREAD

**Issue by nittyjee** [CartoDB/torque#28]
Does Torque not work with polygons, only points?
I am not seeing anything when trying to animate my data.
*Torque attempt: http://bit.ly/1cX0spD
*Map: https://nittyjee.cartodb.com/tables/ames_iowa_buildings/map
*If you want to download and take a look at the data: http://thenittygritty.org/Ames_Iowa_Buildings_Copee.zip

Thanks

**Comment by zerahs** [comment]
Hi,

Do you have any update on this ?  Or any idea when/if the feature will be released ?

Thanks.

**Comment by javisantana** [comment]
I don't think we will work on this, at least of torque

**Comment by knutole** [comment]
Can points be styled to look like squared polygons, though?
