### ISSUE TITLE
Rendering problem with Firefox

### ISSUE THREAD

**Issue by rochoa** [CartoDB/torque#280]
This replaces https://github.com/CartoDB/cartodb/issues/11466.

### Context
Torque visualizations don't work well in Firefox v51. 

Tiles are rendered, but for some of them are not 'cleared' and the result is similar to having the 'cumulative' option enabled. 

This happens only in Firefox, and not on every tile, as some of them work as expected. 
 

### Steps to Reproduce

1. Make sure you're using Firefox v51
2. Open this map https://team.carto.com/u/ernestomb/builder/cd37d292-ec93-11e6-9e93-0e3ebc282e83/embed
3. Check that markers are not cleared and they start accumulating, but only on some of the tiles

### Current Result

Torque maps aren't working well on Firefox

![screen shot 2017-02-06 at 18 51 37](https://cloud.githubusercontent.com/assets/10940006/22659278/57ee3c9c-ec9d-11e6-80f7-2c706eceda14.png)

 

### Expected result

Markers should be cleared from the map 

### Browser and version

 Firefox v51

**Comment by rochoa** [comment]
This seems related to the old trick we use to clear the canvas, see https://github.com/CartoDB/torque/blob/d218c2da24709b1d730e43673379035e26546935/lib/torque/renderer/point.js#L92.

Doing a quick test using [`clearRect`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clearRect) seems to fix the problem in Firefox, however, that might not work for other browsers (e.g. IE).

I tested with:
```
diff --git a/lib/torque/renderer/point.js b/lib/torque/renderer/point.js
index 5dce63a..609086c 100644
--- a/lib/torque/renderer/point.js
+++ b/lib/torque/renderer/point.js
@@ -89,7 +89,7 @@ var CartoDatasource = require('./datasource');
         var color = this._Map['-torque-clear-color']
         // shortcut for the default value
         if (color  === "rgba(255, 255, 255, 0)" || !color) {
-          this._canvas.width = this._canvas.width;
+          this._ctx.clearRect(0, 0, canvas.width, canvas.height);
         } else {
           var ctx = this._ctx;
           ctx.setTransform(1, 0, 0, 1, 0, 0);
```

As we were already using the `width` trick, I guess it's not a problem to ignore previous transformations. Otherwise, it's important to consider them, see http://stackoverflow.com/a/6722031.

**Comment by javisantana** [comment]
clearRect is the right way but we used that trick because it was faster (probably no longer true)

**Comment by donflopez** [comment]
Thanks, @rochoa! That was easy with your help!

As your link to StackOverflow says, we have to reset the transform to have a correct clearRect over the whole canvas.

There is not an important performance change.
- Old trick:
![screen shot 2017-02-08 at 10 21 22](https://cloud.githubusercontent.com/assets/463462/22730834/cdcb7b54-ede8-11e6-80a2-e6c7da94ad0c.png)

- .clearRect with reset:
![screen shot 2017-02-08 at 10 21 30](https://cloud.githubusercontent.com/assets/463462/22730848/de43d648-ede8-11e6-8e05-166a92f45800.png)

I'll make a PR :)

**Comment by donflopez** [comment]
PR [here](https://github.com/CartoDB/torque/pull/281)

**Comment by dgaubert** [comment]
Do you some guidance to do acceptance check here?

**Comment by donflopez** [comment]
The acceptance is the same that the issue describes

**Comment by dgaubert** [comment]
I'm a newbie in Torque's world. My guess is that I'll need some setup in my local env to link the `hotfix-branch` to out stack and test it. Do you know what I'll need?

**Comment by donflopez** [comment]
Ouch, sorry, the prerequisites:

- npm i
- make
- serve the root folder with any server
- open /examples/navy_leaflet.html

**Comment by dgaubert** [comment]
![screen shot 2017-02-08 at 15 29 45](https://cloud.githubusercontent.com/assets/1936888/22741455/967b2c28-ee13-11e6-856e-81a8f4323014.png)

LGTM 🇨🇭

**Comment by donflopez** [comment]
Cool!! Thanks @dgaubert!!

**Comment by rochoa** [comment]
Have you tested this in other browsers? Internet Explorer?

**Comment by donflopez** [comment]
Me not, are we supporting IE @rochoa?

**Comment by dgaubert** [comment]
I've tested only for: firefox and chrome

**Comment by rochoa** [comment]
We do. We need to test IE9+ and Edge. Also, don't forget Safari.

**Comment by dgaubert** [comment]
Safari 10.0.1 (11602.2.14.0.7): 🆗

**Comment by donflopez** [comment]
Ups, I didn't know it! Is there any windows laptop to try?

**Comment by rochoa** [comment]
What's the status on the IE testing?

For IE you can use https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/.

**Comment by donflopez** [comment]
Trying!

**Comment by donflopez** [comment]
It is working as expected! :)

![screen shot 2017-02-13 at 12 08 06](https://cloud.githubusercontent.com/assets/463462/22881109/4cc20220-f1e5-11e6-879f-c5de2f55f376.png)

**Comment by rochoa** [comment]
What about older versions? I'm worried about IE9, see http://stackoverflow.com/a/4085780.

**Comment by donflopez** [comment]
It doesn't work on IE9, but It didn't work before this changes, there are other problems @rochoa

**Comment by donflopez** [comment]
I've tested on IE10 and it works

**Comment by rochoa** [comment]
Then I would :shipit:.

**Comment by ernesmb** [comment]
Will this fix also work for maps created with cartodb.js?

**Comment by donflopez** [comment]
I'm not sure about the differences, sorry... but I'd say yes. Maybe @rochoa or @alonsogarciapablo can say more about this :)

**Comment by rochoa** [comment]
I won't if we don't release new versions of cartodb.js. @ernesmb Can you be more specific about what version you are talking about?

**Comment by ernesmb** [comment]
yes sorry, clients are asking about cartodb.js v3.12.11

let me ask them again just to be 100% sure

sorry for the noise

**Comment by rochoa** [comment]
OK, after talking to @ernesmb about this offline, we would release a new version of cartodb.js v3.15.x to address the issue.

**Comment by donflopez** [comment]
It is deployed in production, closing

**Comment by rochoa** [comment]
@ernesmb, @donflopez just published a new version of cartodb.js including the fixes.
