### ISSUE TITLE
Trigger error when torque tile request fails

### ISSUE THREAD

**Issue by xavijam** [CartoDB/torque#287]
Related ticket: https://github.com/CartoDB/cartodb.js/issues/1717

When the user reaches its limits, torque tiles could be affected, so the idea is to warn CARTO.js about that problem and then it should trigger that error accordingly.

## Caveats

- We need to research if we could "render"/draw an error tile in the torque canvas.

**Comment by rubenmoya** [comment]
Close via #288

**Comment by xavijam** [comment]
Pero que buenos sois.
