### ISSUE TITLE
allow https for Torque layer in the examples of developer center

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/torque#297]
Right now, the examples of the developer center are not displaying the CARTO layers of Torque.
We need to use the https CARTO.js v3 library and allow https for the Torque layer when loading it into the maps.

![screenshot 2018-11-12 at 11 38 05](https://user-images.githubusercontent.com/11177693/48342242-709e9700-e66f-11e8-90c8-4c1a3bec0373.png)

cc @inigomedina

**Comment by inigomedina** [comment]
Nice, @oriolbx! 👏

**Comment by oriolbx** [comment]
This issue can be closed. Solved [here](https://github.com/CartoDB/support/issues/1842). The examples are working now.
