### ISSUE TITLE
document tile format

### ISSUE THREAD

**Issue by javisantana** [CartoDB/torque#32]
see and update https://github.com/andrewxhill/tilecubes

since windshaft supports torque tiles we should create a public document with the tile format spec

**Comment by javisantana** [comment]
reference spec: https://github.com/andrewxhill/tilecubes/blob/master/2.0/spec.md

**Comment by fdansv** [comment]
This is already being worked on internally. Feel free to open issues on specific improvements to the spec.

**Comment by strk** [comment]
The ticket was about a "public document". Working on it internally doesn't make this issue solved :)
