### ISSUE TITLE
Max zoom 22

### ISSUE THREAD

**Issue by tiangolo** [CartoDB/torque#55]
I'm creating a torque visualization at cartodb.com, I'm using fine-grained georeferenced data. The differences between points are just meters.

I set the basemap as "custom" (white color) to be able to zoom as much as is possible. 
At zoom level 22 I can see the torque animation, but once I go to zoom 23 or more, the animation disappears.

**Comment by fdansv** [comment]
This is a problem with our fork of CartoCSS, which has an established maximum zoom of 22. I've tried changing the max zoom value, but the results renderer are pretty unpredictable. I'm opening an issue in Carto and closing this one.
