### ISSUE TITLE
where are all the foos in torqueLayer.on('foo', ...)?

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/torque#91]
I'm working on the documentation of Torque right now. Where can I find all the `torqueLayer.on` events so I can document them?

**Comment by ohasselblad** [comment]
Ok, I gave it a shot:

1. play
2. stop
3. load
4. pause
5. change:time
6. change:steps

Is that it?

**Comment by fdansv** [comment]
There's also 'change:bounds'. You can actually check all events fired by [looking for 'fire'](https://github.com/CartoDB/torque/search?utf8=%E2%9C%93&q=fire&type=Code) in the repo. There are a couple of them which are only really used internally, hence we can leave them undocumented.
