### ISSUE TITLE
cartodb.github.io/torque/ doesn't display torque data

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/torque#95]
I get the following errors when on http://cartodb.github.io/torque/

Seems related to #93 

![screen shot 2015-01-16 at 11 03 34](https://cloud.githubusercontent.com/assets/1041056/5779265/6973cbaa-9d6f-11e4-8fce-51d209815700.png)

**Comment by fdansv** [comment]
Oh, it seems like the vendor directory in gh-pages has the wrong version of Carto. Will fix shortly.

**Comment by ohasselblad** [comment]
I'm not sure that's it because I'm running it locally on master and it does the same thing

**Comment by fdansv** [comment]
It was a combination of outdated version and using the wrong dist of torque. It's working now!

**Comment by ohasselblad** [comment]
nice work :+1:
