### ISSUE TITLE
Make it possible to colour image markers via marker-fill

### ISSUE THREAD

**Issue by fdansv** [CartoDB/torque#96]

**Comment by javisantana** [comment]
low priority right now

**Comment by saleiva** [comment]
This is torque, right?

**Comment by fdansv** [comment]
yep!

**Comment by saleiva** [comment]
Yep, low priority

**Comment by fdansv** [comment]
Yeah I assumed. Just leaving it here for future updates.

**Comment by fdansv** [comment]
This is already happening by setting ```image-filters: colorize()``` with just one color and full opacity, example:

```css
marker-file: url(star.png);
image-filters: colorize(blue);
marker-fill-opacity: 1;
```
![screen shot 2015-02-03 at 15 06 32](https://cloud.githubusercontent.com/assets/3707222/6021489/7e2d0f52-abb6-11e4-9eaf-78903a838f66.png)
