### ISSUE TITLE
getTimeSpan doesn't return anything

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/torque#98]
https://github.com/CartoDB/torque/blob/master/lib/torque/leaflet/torque.js#L349

**Comment by javisantana** [comment]
<3

**Comment by fdansv** [comment]
@danicarrion in the future, it's best to link the line at the current commit at the time. In this case that would be https://github.com/CartoDB/torque/blob/24413a706fbd12348fa8c700cdd622b452f46ea8/lib/torque/leaflet/torque.js#L349

That way the line points at the right place regardless changes to the file ;)
