### ISSUE TITLE
'change:time' is not triggered for the initial animation step

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/torque#99]
When torque loads and starts, the first time 'change:time' is triggered, animation is already in step 1, not in step 0 (i.e., getStep() returns 1).

This snippet can be used to reproduce this:
```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Torque/Infowindow test</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="http://cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/themes/css/cartodb.css">
    </head>
    <body>
        <style>
            #map {
                position: absolute;
                top: 0;
                right: 0;
                bottom: 0;
                left: 0;
            }
        </style>
        <div id="map"></div>
        <script src="http://cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/3.11/cartodb.js"></script>
        <script>
            cartodb.createVis('map', 'http://team.cartodb.com/api/v2/viz/84c7bba2-9d77-11e4-8ccb-0e9d821ea90d/viz.json', {
                zoom: 3,
                center_lat: 5,
                center_lon: 0,
                loaderControl: false,
                zoomControl: false
            }).done(function (vis, layers) {
                torqueLayer = layers[2];
                torqueLayer.on('change:time', function () {
                    console.log(torqueLayer.getStep());
                });
            });
        </script>
    </body>
</html>
```

**Comment by javisantana** [comment]
this is expected since it should be raised on change

**Comment by danicarrion** [comment]
well, this is a bit subjective, but for me "start" implies "change", don't
you think?

2015-01-20 14:55 GMT+01:00 javi santana <notifications@github.com>:

> this is expected since it should be raised on change
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/torque/issues/99#issuecomment-70656241>.
>



-- 
Daniel Carrión
daniel@cartodb.com

**Comment by javisantana** [comment]
we follow backbone pattern for "change" events and that means raising triggers only on real changes

**Comment by danicarrion** [comment]
ok (which means I don't agree with backbone, but I'll live with that ;-) )

thanks

2015-01-21 10:13 GMT+01:00 javi santana <notifications@github.com>:

> we follow backbone pattern for "change" events and that means raising
> triggers only on real changes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/torque/issues/99#issuecomment-70805859>.
>



-- 
Daniel Carrión
daniel@cartodb.com

**Comment by javisantana** [comment]
we could change but we should then change that pattern everywhere in cartodb :P

**Comment by danicarrion** [comment]
no thanks, I don't want everyone to hate me just yet!

2015-01-21 10:22 GMT+01:00 javi santana <notifications@github.com>:

> we could change but we should then change that pattern everywhere in
> cartodb :P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/torque/issues/99#issuecomment-70806913>.
>



-- 
Daniel Carrión
daniel@cartodb.com
